#!/usr/bin/env python3
"""
Generate .env file with secure random keys for IAM Backend
Run this once during initial setup
"""

import secrets
import os

# Generate secure keys
SECRET_KEY = secrets.token_urlsafe(32)
ED25519_SECRET_HEX = secrets.token_hex(32)

# .env file content
ENV_CONTENT = f"""# ========================================
# IAM Backend Configuration
# Auto-generated on setup
# ========================================

# ---------- Security ----------
# Secret key for JWT signing (KEEP SECRET!)
SECRET_KEY={SECRET_KEY}

# JWT token expiration (seconds) - Default: 4 hours (14400s)
JWT_EXP_SECONDS=14400

# ---------- Database ----------
# SQLite for development (use PostgreSQL in production)
DATABASE_URL=sqlite:///./iam.db

# PostgreSQL example (uncomment for production):
# DATABASE_URL=postgresql://user:password@localhost:5432/iam_db

# ---------- QR Authentication ----------
# QR scan window (seconds) - How long user has to scan QR after login
QR_TTL_SECONDS=60

# QR value entropy (bytes) - Length of random QR value
QR_BYTES=20

# ---------- Network Security ----------
# IP ranges allowed to access the system (CIDR format)
# Default: localhost + common private networks
ALLOWED_IP_RANGES=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

# Production example (restrict to specific network):
# ALLOWED_IP_RANGES=192.168.1.0/24,10.0.50.0/24

# ---------- File Upload ----------
# Maximum file size for photo uploads (bytes) - Default: 15MB
MAX_CONTENT_LENGTH=15728640

# ---------- Event Signing (Audit Log) ----------
# Ed25519 secret key for blockchain-like event signing
ED25519_SECRET_HEX={ED25519_SECRET_HEX}

# Alternative: path to store Ed25519 key (if not using hex above)
# ED25519_SECRET_PATH=ed25519_secret.hex

# ---------- Camera Monitoring ----------
# Camera URLs for monitoring dashboard (Format: Name|URL,Name2|URL2)
# Default: Simulated cameras for testing
CAM_URLS=Cam 1|/camera_sim/1,Cam 2|/camera_sim/2,Cam 3|/camera_sim/3,Cam 4|/camera_sim/4

# Production example with real cameras:
# CAM_URLS=Entrance|rtsp://192.168.1.100:554/stream,Office|http://192.168.1.101/video,Parking|rtsp://192.168.1.102:554/stream

# ---------- CORS ----------
# Allowed origins for CORS (comma-separated)
# Default: Allow all (use specific origins in production)
CORS_ORIGINS=*

# Production example:
# CORS_ORIGINS=https://yourdomain.com,https://app.yourdomain.com

# ---------- Server-Sent Events ----------
# Maximum concurrent SSE connections for log streaming
MAX_SSE_LISTENERS=100

# ---------- TLS/HTTPS Configuration ----------
# Certificate paths (generated by generate_certs.py)
TLS_CERT_FILE=certs/server/server-fullchain.crt
TLS_KEY_FILE=certs/server/server.key
# Port for HTTPS (5443 for development, 443 for production)
HTTPS_PORT=5443
"""

def main():
    env_file = ".env"
    
    if os.path.exists(env_file):
        response = input(f"\n[WARNING] {env_file} already exists. Overwrite? (y/N): ")
        if response.lower() not in ('y', 'yes'):
            print("[CANCELLED] Keeping existing .env file")
            return
    
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(ENV_CONTENT)
    
    print("\n[SUCCESS] .env file created successfully!")
    print(f"\n[*] Location: {os.path.abspath(env_file)}")
    print("\n[*] Generated Keys:")
    print(f"    SECRET_KEY: {SECRET_KEY[:20]}... (32 chars)")
    print(f"    ED25519_SECRET_HEX: {ED25519_SECRET_HEX[:20]}... (64 chars)")
    print("\n[SECURITY] Keep these keys secret! Do not commit .env to version control.")
    print("\n[NEXT STEPS]")
    print("  1. Review and customize .env file if needed")
    print("  2. Run: python -m app.cli create-admin --uid ADMIN-1 --email admin@local --password YourPassword123!")
    print("  3. Run HTTPS server: python run_https.py")
    print("  4. Access: https://localhost:5443")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n[ERROR] {e}")
        exit(1)


